var car = 'subaru';
var age = 25;
var numericals = [1, 2, 3, 4];
console.log(car == 'subaru');
console.log(car != 'subaru');
console.log(car.toLowerCase() == 'faraz');
console.log(car.toLowerCase() != 'faraz');
console.log(age == 25);
console.log(age != 25);
console.log(age > 25);
console.log(age < 25);
console.log(age >= 25);
console.log(age <= 25);
console.log(age > 20 && age < 30);
console.log(age > 20 || age < 30);
console.log(3 in numericals);
console.log(5 in numericals);
console.log(numericals.includes(3));
console.log(numericals.includes(6));
